### PR TITLE
Abstracts the Firebase functions into their own .js file for reuse ar…

### PR DESCRIPTION
**Pull request by philals**
…ound the place

@pjho 

I have redone this uptodate with DEV

Would it be best to pass the function of update & delete player to that component or we could pass down the FirebaseLib object?

### CODE REVIEW

**Comment by philals** [comment]
Sorry it's open.. I clicked the close button for some reason

**Comment by pjho** [comment]
Best to pass the functions down. [Here's a good article](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) about 'smart' and 'dumb' components. Basically you want to have as much logic occuring at the higher level 'smart' component as it makes state & state change easier to trace and the sub components more portable.

**Comment by philals** [comment]
Cool. I'll give that a read. Good learning stuff. This PR is good to go if you think it's a good idea.

**Comment by pjho** [comment]
cool, looks good. We're gonna have the PlayerDash firebase methods to add to it soon as well :)

**Comment by philals** [comment]
Yeah, I saw that. I branched off MASTER then had conflicts so had to redo it branched of DEV lol

**Comment by pjho** [comment]
:+1:

**Pull request merged**
