### PR TITLE
Adds history.pushstate support to dev server for cleaner URLs.

### PR DESCRIPTION
**Pull request by pjho**
@philals 

This branch updates the ReactRouter History method to use PushState/BrowserHistory which results in much cleaner URLs. i.e. `/player/~ABCD12345` instead of `/#/player/~ABCD12345?k=asdaasdasd`

Locally the gulp file/browserSync server is configured to route all page requests to index.html. We will need to host on a server with equivalent capability. Github pages can do this by using 200.html instead of index.html as without the index all successful (HTTP 200) requests will route to this file. So I'll need to have auth working fro next release, and we can move to a different domain.

### CODE REVIEW

**Comment by philals** [comment]
Would it be a good idea to accept this now or wait until we have another host lined up? I think the graphing is really close. Pretty much there as is.

**Comment by pjho** [comment]
yeah true dat, lets hold this one for next release...

**Comment by pjho** [comment]
@philals I've merged this, I want to make it a config so it can be shut off easily if hosting on dropbox or similar so I've pulled in and will adjust..

**Comment by philals** [comment]
@pjho Cool man. Don't let me slow you down. Go nuts!

**Pull request merged**
